"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 100000

[nodejs]
format = "using Node.js [ğŸ¤– $version](bold green) "

[php]
format = "using PHP [ğŸ˜ $version](147 bold) "

[python]
format = "using Python [ğŸ $version](bold yellow) "

[git_branch]
format = "on [$symbol$branch]($style) branch "
style = "bold yellow"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ–](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
